# Generated by Django 4.2.30 on 2026-06-21 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import trips.models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='openid',
        ),
        migrations.AddField(
            model_name='expense',
            name='payer_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_expenses', to='trips.travelmember'),
        ),
        migrations.AddField(
            model_name='expense',
            name='split_type',
            field=models.CharField(choices=[('equal', '平摊'), ('amount', '按金额')], default='equal', max_length=16),
        ),
        migrations.AddField(
            model_name='expenseshare',
            name='share_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='cat_fund',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='travel',
            name='settings',
            field=models.JSONField(default=trips.models.default_travel_settings),
        ),
        migrations.AddField(
            model_name='travelmember',
            name='can_bookkeep',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('enabled', '启用'), ('disabled', '禁用')], default='enabled', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='trips.travel'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_travels', to='trips.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name='expenseshare',
            unique_together={('expense', 'member')},
        ),
        migrations.AlterModelTable(
            name='expense',
            table='expenses',
        ),
        migrations.AlterModelTable(
            name='expenseshare',
            table='expense_shares',
        ),
        migrations.AlterModelTable(
            name='settlement',
            table='settlements',
        ),
        migrations.AlterModelTable(
            name='travel',
            table='travels',
        ),
        migrations.AlterModelTable(
            name='travelmember',
            table='travel_members',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.CreateModel(
            name='WechatBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appid', models.CharField(max_length=128)),
                ('openid', models.CharField(max_length=128)),
                ('unionid', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('bound_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unbound_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wechat_bindings', to='trips.travel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wechat_bindings', to='trips.user')),
            ],
            options={
                'db_table': 'wechat_bindings',
                'indexes': [models.Index(fields=['travel', 'appid', 'openid', 'is_active'], name='wechat_bind_travel__26faab_idx'), models.Index(fields=['travel', 'user', 'is_active'], name='wechat_bind_travel__0bfd0a_idx')],
            },
        ),
    ]
