# Generated by Django 4.2.30 on 2026-06-21 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_expense_payer_remove_user_openid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_travels', to='trips.user'),
        ),
    ]
